# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Cloud Functions Deploy
        # You may pin to the exact commit or the version.
        # uses: google-github-actions/deploy-cloud-functions@7faa962492ec7b650406d15004fc19c6880f94d0
        uses: google-github-actions/deploy-cloud-functions@v0.1.2
        with:
          # Optional service account key to use for authentication to GCP. This should be the JSON
          # formatted private key which can be exported from the Cloud Console. The
          # value can be raw or base64-encoded.
          credentials: {{ secrets.gcp_credentials }}
          # Name of the Cloud Function.
          name: hello world
          # Description for the Cloud Function.
          description: test description
          # Project to deploy the function in.
          project_id: root-sanctuary-276107
          # Region to deploy the function in. Defaults to us-central1, if not specified.
          region: us-central1
          # Name of a function (as defined in source code) that will be executed. Defaults to the resource name suffix, if not specified. 
          entry_point: insert_data
          # Runtime to use for the function.
          runtime: python38
      
